### ISSUE TITLE
关于树莓派上的唤起问题

### ISSUE THREAD

**Issue by Colbert337** [luyishisi/python_yuyinduihua#1]
简单看了实现，发现是通过命令行执行arecord进行记录，需要用while(true)一直循环跑。
我的问题：由于麦克风可能有杂音和背景音，能不能做到音量大到一定程度，才唤起语音识别？

另外还有过问题，目录里面有好多py，哪个才是最终的程序？luyin.py还是main.py？

**Comment by seeseeatre** [comment]
可以参考：
https://github.com/WChurchill/ais-demos/blob/36442769bd248713c906584cf1fbc646b84a0c30/jarvis/start_speech_bot.py
